#!/usr/bin/env bash

declare -i page=1

function help() {
  cat <<EOF
Leta Searcher

Usage:
  search FLAG QUERY
  search -h | search help

Flags:
  -h               Displays this message and exits
  -s SEARCH        Search in the terminal
EOF
}

function version() {
  echo "0.2.0"
}

function _rofi() {
  local div_color="#334433"
  local HELP
  local help_color="#7c5cff"
  local label="#f067fc"
  local next="Ctrl+1"
  local prev="Ctrl+2"
  local restart="Alt-r"
  HELP="<span color='${label}'>Actions: </span> <span color='${help_color}'>${next}</span>: Next Page <span color='${div_color}'>|</span> <span color='${help_color}'>${prev}</span>: Previous Page"
  rofi -dmenu -i -no-levenshtein-sort -width 1000 -mesg "${HELP}" -kb-custom-1 "${restart}" -kb-custom-2 "${next}" -kb-custom-3 "${prev}" "$@"

  val=$?
  case "$val" in
  10)
    main
    ;;
  11)
    page+=1
    main
    ;;
  12)
    page+=-1
    if [ "$page" -lt 1 ]; then
      page=1
    fi
    main
    ;;
  esac
}

function _fzf() {
  local HEADER NEXT_PAGE PREV_PAGE
  export fzf_page=1
  HEADER=" A-n: Next Page / A-p: Previous Page"
  NEXT_PAGE="alt-n:reload(fzf_page=\$((fzf_page + 1)); python leta-searcher.py $search --page \$fzf_page)"
  PREV_PAGE="alt-p:reload(fzf_page=\$((fzf_page - 1)); [ \$fzf_page -lt 1 ] && fzf_page=1; python leta-searcher.py $search --page \$fzf_page)"

  fzf --tmux 88% \
    --bind "$NEXT_PAGE" \
    --bind "$PREV_PAGE" \
    --header "$HEADER" \
    --preview-window up:67%
}

function get_input() {
  if [ -z "$mode" ]; then
    search=$(echo "" | _rofi -p "> " -mesg "Enter your Search: " | sed 's/ /+/')
  fi
  [[ -z $search ]] && exit 1
}

function main() {
  if [ "$mode" == "sh" ]; then
    select=$(python "$(dirname "$0")/leta-searcher.py" "$search" | _fzf | awk -F ". " '{print $2}')
  else
    select=$(python "$(dirname "$0")/leta-searcher.py" "$search" --page "$page" | _rofi -p "󰖟 " | awk -F ". " '{print $2}')
  fi
  if [ "$mode" == "sh" ]; then
    [[ -z $select ]] && exit 1
    if command -v lynx &>/dev/null; then
      lynx -cookies "$select"
    else
      xdg-open "$select" >/dev/null
    fi
  else
    xdg-open "$select" >/dev/null
  fi
}

while getopts ":hs" opt; do
  case "$opt" in
  h)
    help
    exit 0
    ;;
  s)
    mode="sh"
    ;;
  ?)
    echo "Error: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

search=${*// /+/}
get_input

main
