#!/usr/bin/env bash

mode=$1
shift
args=$*
restart="Alt-r"

if ! command -v lynx; then
  echo "This script requires Lynx. Please install it."
fi

function get_urls() {
  if command -v lynx; then
    lynx -dump "https://leta.mullvad.net/search?q=$query&engine=brave" | rg --no-line-number '  https://' | tr -d " "
    return 0
  elif command -v htmlq; then
    curl -s "https://leta.mullvad.net/search?q=tor+browser&engine=brave" |
      htmlq -a href a |
      rg '^https?://' |
      tr -d " "
    return 0
  elif command -v pup; then
    curl -s "https://leta.mullvad.net/search?q=tor+browser&engine=brave" |
      pup 'a attr{href}' |
      rg '^https?://' |
      tr -d " "
    return 0
  else
    echo "You must have one these installed to properly run search:"
    echo -e "Lynx\nCurl + HTMLQ\nCurl + PUP"
    exit 1
  fi
}

function _rofi() {
  rofi -dmenu -i -no-levenshtein-sort -width 1000 -kb-custom-1 "${restart}" "$@"
}

function get_input() {
  if [ "$mode" == "sh" ]; then
    search=$args
    echo "$search"
  else
    search=$(echo "" | _rofi -p "> " -mesg "Enter your Search: ")
  fi
  [[ -z $search ]] && exit 1
  query=$(echo "$search" | sed 's/ /+/')
}

function main() {
  get_input
  if [ "$mode" == "sh" ]; then
    select=$(get_urls | fzf)
  else
    select=$(get_urls | _rofi -p "󰖟 ")
  fi
  val=$?
  case "$val" in
  10)
    main
    ;;
  esac
  if [ "$mode" == "sh" ]; then
    [[ -z $select ]] && exit 1
    if command -v lynx; then
      lynx -cookies $select
    else
      xdg-open "$select" >/dev/null
    fi
  else
    xdg-open "$select" >/dev/null
  fi
}

main
